/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
static yyconst short int yy_accept[179] =
    {   0,
        0,    0,    0,    0,    0,    0,   61,   60,   59,   60,
       36,   37,   33,   31,   40,   39,   55,   55,   42,   38,
       30,   41,   30,   43,   44,   60,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   47,   48,   49,   50,    0,    0,    0,
       46,   58,   58,    0,    0,    0,   55,   45,   30,   54,
       54,    0,   54,   54,   54,   54,   54,   54,   54,   22,
       54,   54,   54,   54,   18,   35,   54,   54,    6,   32,
       54,   54,   54,   54,   25,   54,   54,   54,   54,   54,
       54,   48,   51,   52,    0,    0,   58,   56,   57,   33,

       54,   54,   54,   54,   54,   54,   54,   17,   23,   54,
       54,   34,   54,   54,   54,    5,   54,   54,   54,    8,
       54,   54,   54,   53,   56,   57,   54,   54,   54,   15,
       54,   54,   20,   54,   54,   54,   54,   54,   27,   13,
       54,   19,   29,    3,   54,   26,   54,    4,   16,   54,
        2,   54,   54,   54,   54,   54,   54,   54,   21,   28,
       54,   24,   54,   54,   54,   54,   54,    7,   14,    9,
       54,   12,   54,    1,   10,   54,   11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    4,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    3,    3,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   45,   34,   46,   34,
       21,   22,   23,    3,   24,    3,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,   34,   35,   36,   37,
       38,   39,   34,   40,   41,   42,   43,   44,   45,   34,
       46,   34,   47,    3,   48,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    2
    } ;

static yyconst short int yy_base[186] =
    {   0,
        0,    0,   47,   48,    0,    0,  410,  411,  411,   94,
      411,  411,  411,  411,  411,   40,   41,   45,  390,  411,
       42,  411,  389,  411,  411,    0,   39,   40,   33,   42,
       46,   44,  383,  119,   48,   50,  120,   53,   60,   61,
      121,   67,  122,  411,    0,  411,  411,  402,  401,  143,
      411,  150,  157,  161,  390,    0,  175,  411,  411,  379,
      378,  377,  124,  142,  127,  153,  154,  144,  160,  168,
      169,  170,  171,  172,  376,  173,  175,  176,  375,  374,
      178,  181,  177,  183,  373,  190,  193,  196,  197,  198,
      201,    0,  411,  411,  392,  213,  224,  210,    0,  371,

      217,  211,  219,  205,  207,  222,  223,  370,  225,  226,
      227,  369,  231,  233,  236,  368,  239,  240,  242,  367,
      243,  241,  248,  411,  266,    0,  251,  257,  253,  366,
      259,  260,  365,  261,  263,  264,  267,  268,  364,  363,
      269,  362,  360,  356,  274,  349,  275,  324,  323,  282,
      321,  276,  286,  287,  288,  291,  297,  299,  320,  318,
      292,  315,  300,  294,  301,  306,  307,  314,  313,  312,
      309,  289,  310,  265,  133,  311,   70,  411,  350,  357,
      359,  364,  371,  375,  379
    } ;

static yyconst short int yy_def[186] =
    {   0,
      178,    1,  179,  179,  180,  180,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  181,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  178,  183,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  184,  178,  178,  178,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  183,  178,  178,  178,  178,  178,  178,  185,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  178,  178,  185,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,    0,  178,  178,
      178,  178,  178,  178,  178
    } ;

static yyconst short int yy_nxt[460] =
    {   0,
        8,    9,    8,   10,   11,   12,   13,   14,   15,   14,
       16,   13,   17,   18,   18,   19,   20,   21,   22,   23,
       24,    8,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   33,   34,   33,   33,   35,   36,   37,   38,   39,
       40,   41,   33,   42,   43,   33,   44,    8,   46,   46,
       51,   54,   52,   53,   53,   54,   62,   57,   57,   57,
       59,   59,   62,   62,   67,   62,   55,   62,   65,   62,
       68,   62,   56,   62,   69,   63,   62,   66,   64,   70,
       71,   73,   72,   62,   62,   77,   74,   78,   82,   83,
       62,   88,   81,   62,   47,   47,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   49,   49,   49,   48,
       48,   48,   48,   48,   48,   50,   48,   48,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       48,   48,   62,   62,   62,   62,   93,   62,   75,   79,
       62,  100,   84,   89,   90,   76,   62,  102,   85,   80,
       86,   91,   96,   53,   53,   62,   87,   62,   95,   97,
       97,   97,   95,   52,   53,   53,   62,   62,  104,   95,
      105,  101,   95,   62,   95,   54,   95,   57,   57,   57,
      103,   62,   62,   62,   62,   62,   62,  108,   62,   62,

       62,   62,  100,  100,   62,  114,   62,  115,  110,  107,
      109,  117,  106,   62,  111,  113,   62,  112,  116,   62,
       62,   62,  125,  125,   62,   96,   53,   53,   62,  121,
       62,  119,  118,  123,   62,  120,   97,   97,   97,  122,
       62,  127,   62,  128,  130,   62,   62,  131,   62,   62,
       62,  133,  135,  129,   62,  136,   62,  137,  132,   62,
      139,  138,   62,   62,   62,   62,   62,  140,  143,  134,
      144,   62,  146,  141,   62,  142,   62,  145,  125,  125,
       62,  150,   62,   62,   62,  153,   62,   62,   62,  147,
       62,   62,   62,  149,  155,  156,  148,   62,   62,   62,

      151,  152,  159,  160,  154,   62,  161,  157,  158,   62,
       62,   62,   62,  162,   62,   62,  165,   62,  166,  164,
       62,  167,   62,   62,   62,  163,  168,  170,  169,   62,
       62,  171,   62,   62,   62,   62,   62,   62,   62,  177,
      172,   62,  174,   62,   62,  175,   62,   62,  173,  176,
       45,   45,   45,   45,   45,   45,   45,    8,    8,    8,
        8,    8,    8,    8,   60,   60,   61,   61,   61,   61,
       61,   92,   62,   92,   92,   92,   92,   92,   99,   62,
       99,  126,  126,   62,  126,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,  124,   62,   62,   62,   62,

       62,   62,   62,   98,   94,   93,   62,   59,   58,  178,
        7,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178
    } ;

static yyconst short int yy_chk[460] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       16,   17,   16,   16,   16,   18,   29,   18,   18,   18,
       21,   21,   27,   28,   29,   30,   17,   32,   28,   31,
       29,   35,   17,   36,   30,   27,   38,   28,   27,   30,
       31,   32,   31,   39,   40,   35,   32,   36,   39,   40,
       42,   42,   38,  177,    3,    4,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   34,   37,   41,   43,   50,   63,   34,   37,
       65,   63,   41,   43,   43,   34,  175,   65,   41,   37,
       41,   43,   52,   52,   52,   64,   41,   68,   50,   53,
       53,   53,   50,   54,   54,   54,   66,   67,   67,   50,
       68,   64,   50,   69,   50,   57,   50,   57,   57,   57,
       66,   70,   71,   72,   73,   74,   76,   72,   77,   78,

       83,   81,   77,   69,   82,   82,   84,   82,   74,   71,
       73,   84,   70,   86,   76,   81,   87,   78,   83,   88,
       89,   90,   98,   98,   91,   96,   96,   96,  104,   89,
      105,   87,   86,   91,  102,   88,   97,   97,   97,   90,
      101,  101,  103,  102,  104,  106,  107,  105,  109,  110,
      111,  107,  110,  103,  113,  111,  114,  113,  106,  115,
      114,  113,  117,  118,  122,  119,  121,  114,  118,  109,
      119,  123,  122,  115,  127,  117,  129,  121,  125,  125,
      128,  129,  131,  132,  134,  134,  135,  136,  174,  123,
      137,  138,  141,  128,  136,  137,  127,  145,  147,  152,

      131,  132,  145,  147,  135,  150,  150,  138,  141,  153,
      154,  155,  172,  152,  156,  161,  155,  164,  156,  154,
      157,  157,  158,  163,  165,  153,  158,  163,  161,  166,
      167,  164,  171,  173,  176,  170,  169,  168,  162,  176,
      165,  160,  167,  159,  151,  171,  149,  148,  166,  173,
      179,  179,  179,  179,  179,  179,  179,  180,  180,  180,
      180,  180,  180,  180,  181,  181,  182,  182,  182,  182,
      182,  183,  146,  183,  183,  183,  183,  183,  184,  144,
      184,  185,  185,  143,  185,  142,  140,  139,  133,  130,
      120,  116,  112,  108,  100,   95,   85,   80,   79,   75,

       62,   61,   60,   55,   49,   48,   33,   23,   19,    7,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
/*edw mpainei o kwdikas c*/
#line 4 "lex.l"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include <string.h>

#define T_EOF			0
#define T_PROGRAM		1
#define T_CONST			2
#define T_TYPE			3
#define T_ARRAY			4
#define T_SET			5
#define T_OF			6
#define T_RECORD		7
#define T_VAR			8
#define T_FORWARD		9
#define T_FUNCTION		10
#define T_PROCEDURE		11
#define T_INTEGER		12
#define T_REAL			13
#define T_BOOLEAN		14
#define T_CHAR			15
#define T_BEGIN			16
#define T_END			17
#define T_IF			18
#define T_THEN			19
#define T_ELSE			20
#define T_WHILE			21
#define T_DO			22
#define T_FOR			23
#define T_DOWNTO		24
#define T_TO			25
#define T_WITH			26
#define T_READ			27
#define T_WRITE			28
#define T_BCONST		29
#define T_RELOP			30
#define T_ADDOP			31
#define T_OROP			32
#define T_MULDIVANDOP	33
#define T_NOTOP			34
#define T_INOP			35
#define T_LPAREN		36
#define T_RPAREN		37
#define T_SEMI			38
#define T_DOT			39
#define T_COMMA			40
#define T_EQU			41
#define T_COLON			42
#define T_LBRACK		43
#define T_RBRACK		44
#define T_ASSIGN		45
#define T_DOTDOT		46
#define T_CCONST		47
#define T_ICONST		48
#define T_RCONST		49
#define T_ID			50


int lineno = 1;
extern yylval;

void ERROR (const char msg []);
void Print_String(int token_id);
#define COMMENT 1
 
#define STRING 2

/* mnimonika onomata (under construction) */
#line 596 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 89 "lex.l"


#line 750 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 179 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 411 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 91 "lex.l"
{Print_String(T_PROGRAM); return T_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 93 "lex.l"
{Print_String(T_CONST); return T_CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "lex.l"
{Print_String(T_TYPE); return T_TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "lex.l"
{Print_String(T_ARRAY); return T_ARRAY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 99 "lex.l"
{Print_String(T_SET); return T_SET;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "lex.l"
{Print_String(T_OF); return T_OF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "lex.l"
{Print_String(T_RECORD); return T_RECORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "lex.l"
{Print_String(T_VAR); return T_VAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "lex.l"
{Print_String(T_FORWARD); return T_FORWARD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "lex.l"
{Print_String(T_FUNCTION); return T_FUNCTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "lex.l"
{Print_String(T_PROCEDURE); return T_PROCEDURE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 113 "lex.l"
{Print_String(T_INTEGER); return T_INTEGER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "lex.l"
{Print_String(T_REAL); return T_REAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "lex.l"
{Print_String(T_BOOLEAN); return T_BOOLEAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 120 "lex.l"
{Print_String(T_CHAR); return T_CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "lex.l"
{Print_String(T_BEGIN); return T_BEGIN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "lex.l"
{Print_String(T_END); return T_END;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 126 "lex.l"
{Print_String(T_IF); return T_IF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 128 "lex.l"
{Print_String(T_THEN); return T_THEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "lex.l"
{Print_String(T_ELSE); return T_ELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "lex.l"
{Print_String(T_WHILE); return T_WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 134 "lex.l"
{Print_String(T_DO); return T_DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "lex.l"
{Print_String(T_FOR); return T_FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 138 "lex.l"
{Print_String(T_DOWNTO); return T_DOWNTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 140 "lex.l"
{Print_String(T_TO); return T_TO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 142 "lex.l"
{Print_String(T_WITH); return T_WITH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 144 "lex.l"
{Print_String(T_READ); return T_READ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "lex.l"
{Print_String(T_WRITE); return T_WRITE;}
	YY_BREAK
case 29:
#line 150 "lex.l"
case 30:
YY_RULE_SETUP
#line 151 "lex.l"
{Print_String(T_RELOP); return T_RELOP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 154 "lex.l"
{Print_String(T_ADDOP); return T_ADDOP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 156 "lex.l"
{Print_String(T_OROP); return T_OROP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 158 "lex.l"
{Print_String(T_MULDIVANDOP); return T_MULDIVANDOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 160 "lex.l"
{Print_String(T_NOTOP); return T_NOTOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "lex.l"
{Print_String(T_INOP); return T_INOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 165 "lex.l"
{Print_String(T_LPAREN); return T_LPAREN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 167 "lex.l"
{Print_String(T_RPAREN); return T_RPAREN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "lex.l"
{Print_String(T_SEMI); return T_SEMI;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 171 "lex.l"
{Print_String(T_DOT); return T_DOT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 173 "lex.l"
{Print_String(T_COMMA); return T_COMMA;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 175 "lex.l"
{Print_String(T_EQU); return T_EQU;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 177 "lex.l"
{Print_String(T_COLON); return T_COLON;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 179 "lex.l"
{Print_String(T_LBRACK); return T_LBRACK;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 181 "lex.l"
{Print_String(T_RBRACK); return T_RBRACK;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 183 "lex.l"
{Print_String(T_ASSIGN); return T_ASSIGN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 185 "lex.l"
{Print_String(T_DOTDOT); return T_DOTDOT;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 187 "lex.l"
{Print_String(T_EOF); return T_EOF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 191 "lex.l"
BEGIN(COMMENT);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 192 "lex.l"
;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 193 "lex.l"
{lineno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 194 "lex.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 195 "lex.l"
BEGIN(INITIAL);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 197 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 199 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 201 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "lex.l"
{Print_String(T_ID); return T_ID;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 208 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 211 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 214 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 216 "lex.l"
{lineno++;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 220 "lex.l"
ECHO;
	YY_BREAK
#line 1138 "lex.yy.c"
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 179 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 179 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 178);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 220 "lex.l"


int main() {
	int token;
	
	do {
		token = yylex();
	} while (token != T_EOF);
	
	return 0;
}

void ERROR (const char msg[]) {
	fprintf(stderr, "ERROR, line %d: %s\n", lineno, msg);
	exit(1);
}

void Print_String(int token) {
    //if(FLEX_DEBUG && SHOW_TOKENS){
        printf("TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n\n", yytext, token, lineno);
    //}    
}

int HexToInt(char *str){
    return (int) strtol(&str[2], NULL, 16);
}

int BinToInt(char *str){
    return (int) strtol(&str[2], NULL, 2);
}

int DecInt(char *str) {
	return atoi(str);
}

double DecReal(char *str) {
	return atof(str);
}

